#+property: header-args:R :session *R* :results output :
* Base R EDA and =ggplot2= popquiz

1. Plot f(x) = 5x-3  for x in [0,10].
   #+begin_src R :file linear.png :session *R* :results file graphics output 

   #+end_src

2. Plot f(x) = (1-x)^2 for x in [0,10].
   #+begin_src R :file nonlinear.png :session *R* :results file graphics output 

   #+end_src

3. In base R, plot the measurements before and after insulation in the
   =whiteside= data set (distinguished by the values of =Insul = "Before"=
   and =Insul = "After"=).
   #+begin_src R :file  barplot.png :session *R* :results file graphics output 

   #+end_src

4. Make a pair plot of the variables of the built-in =iris= dataset.
   #+begin_src R :file iris.png :session *R* :results file graphics output 

   #+end_src

5. The built-in data set =AirPassengers= is a time series. It contains
   the monthly totals of international airline passengers from 1949
   to 1960. In base R, make a line plot of the time series data, and
   title it "Monthly number of int. air passengers 1949-1960".
   #+begin_src R :file AirPassengers.png :session *R* :results file graphics output 

   #+end_src

6. In base R, make a histogram of the =AirPassengers= time series, and
   change the default y-axis label to "Count of Int. air passengers".
   #+begin_src R :file AirPassengers2.png :session *R* :results file graphics output 

   #+end_src

7. Plot the statistical =summary= values including the =mean= for the
   =AirPassengers= dataset.
   #+begin_src R :file airbox.png :session *R* :results file graphics output 

   #+end_src

8. Using =ggplot2=, make a histogram of the time series data set
   =AirPassengers= and label the y-axis "Count of int. air passengers")
   #+begin_src R :file airHistggplot2.png :session *R* :results file graphics output 

   #+end_src

9. Using =ggplot2=, plot f(x) = 5x-3  for x in [0,10].
   #+begin_src R :file linPlotggplot2.png :session *R* :results file graphics output 

   #+end_src

10. Using =ggplot2=, plot f(x) = (1-x)^2 for x in [0,10].
    #+begin_src R :file nonLinearPlotggplot2.png :session *R* :results file graphics output 

    #+end_src
